GET http://100.26.253.12:3000/products/
###
GET http://localhost:4000/attendees

###
POST http://localhost:4000/attendees
content-type: application/json

{
      "firstName": "",
      "lastName": "",
      "email": "",
      "shirt": "XS",
      "skillLevel": "beginner"
}
